/****** TOW WITH VEHICLE  ******/

/**
 * List of class names of (ground or air) vehicles which can tow towables objects.
 */
R3F_LOG_CFG_remorqueurs =
[
	"SUV_01_base_F",
	"Offroad_01_base_F",
	"Van_01_base_F",
	"MRAP_01_base_F",
	"MRAP_02_base_F",
	"MRAP_03_base_F",
	"Truck_01_base_F",
	"Truck_02_base_F",
	"Wheeled_APC_F",
	"Tank_F",
	"C_Hatchback_01_F",
	"C_Hatchback_01_sport_F",
	"C_SUV_01_F",
	"C_Offroad_01_F",
	"I_G_Offroad_01_F",
	"C_Van_01_box_F",
	"C_Van_01_transport_F",
	"I_G_Van_01_transport_F",
	"O_Truck_02_covered_F",
	"I_Truck_02_covered_F",
	"O_Truck_02_transport_F",
	"I_Truck_02_transport_F",
	"I_G_Offroad_01_armed_F",
	"I_Truck_02_Fuel_F",
	"O_Truck_02_Fuel_F",
	"I_Truck_02_medical_F",
	"O_Truck_02_medical_F",
	"B_MRAP_01_F",
	"O_MRAP_02_F",
	"I_MRAP_03_F",
	"Boat_Armed_01_base_F",
	"ArmoredSUV_PMC",
	"BAF_Jackal2_L2A1_D",
	"BAF_Jackal2_L2A1_w",
	"BMP3",
	"B_APC_Tracked_01_AA_F",
	"B_APC_Tracked_01_CRV_F",
	"B_APC_Tracked_01_rcws_F",
	"B_APC_Wheeled_01_cannon_F",
	"B_MBT_01_arty_F",
	"B_MBT_01_cannon_F",
	"B_MBT_01_mlrs_F",
	"B_MRAP_01_F",
	"B_MRAP_01_gmg_F",
	"B_MRAP_01_hmg_F",
	"B_MRAP_01_hmg_F", 
	"B_Truck_01_ammo_F",
	"B_Truck_01_box_F",
	"B_Truck_01_covered_F",
	"B_Truck_01_fuel_F",
	"B_Truck_01_medical_F",
	"B_Truck_01_mover_F",
	"B_Truck_01_Repair_F",
	"B_Truck_01_transport_F",
	"C_Hatchback_01_F",
	"C_Hatchback_01_sport_F",
	"C_Offroad_01_F",
	"O_MBT_02_arty_F",
	"O_MBT_02_cannon_F",
	"O_MRAP_02_F",
	"O_MRAP_02_gmg_F",
	"O_MRAP_02_hmg_F",
	"O_MRAP_02_hmg_F", 
	"C_Van_01_box_F",
	"C_Van_01_box_F", 
	"C_Van_01_fuel_F",
	"C_Van_01_transport_F",
	"Hatchback_01_base_F",
	"I_APC_Wheeled_03_cannon_F",
	"I_G_Offroad_01_armed_F",
	"I_G_Offroad_01_F",
	"I_MRAP_03_F",
	"I_MRAP_03_gmg_F",
	"I_MRAP_03_hmg_F",
	"I_Truck_02_ammo_F",
	"I_Truck_02_box_F",
	"I_Truck_02_covered_F",
	"I_Truck_02_fuel_F",
	"I_Truck_02_medical_F",
	"I_Truck_02_transport_F",
	"M1128_MGS_EP1",
	"M1133_MEV_EP1",
	"MRAP_01_base_F",
	"MRAP_02_base_F",
	"MRAP_03_base_F",
	"Offroad_01_base_F",
	"O_APC_Tracked_02_AA_F",
	"O_APC_Tracked_02_cannon_F",
	"O_APC_Wheeled_02_rcws_F",
	"O_MBT_02_arty_F",
	"O_MBT_02_cannon_F",
	"O_MRAP_02_F",
	"O_MRAP_02_gmg_F",
	"O_MRAP_02_hmg_F",
	"O_MRAP_02_hmg_F", 
	"O_Truck_02_Ammo_F",
	"O_Truck_02_box_F",
	"O_Truck_02_covered_F",
	"O_Truck_02_Fuel_F",
	"O_Truck_02_medical_F",
	"O_Truck_02_transport_F",
	"O_Truck_03_ammo_F",
	"O_Truck_03_fuel_F",
	"O_Truck_03_medical_F",
	"T34",
	"T55_TK_GUE_EP1",
	"Tank_F",
	"Truck_01_base_F",
	"Truck_02_base_F",
	"Van_01_base_F",
	"Wheeled_APC_F"
];

/**
 * List of class names of towables objects.
 */
R3F_LOG_CFG_object_towables =
[
	"ArmoredSUV_PMC",
	"BAF_Jackal2_L2A1_D",
	"BAF_Jackal2_L2A1_w",
	"BMP3",
	"Boat_Armed_01_base_F",
	"BTR40_MG_TK_GUE_EP1",
	"B_APC_Tracked_01_AA_F",
	"B_APC_Tracked_01_CRV_F",
	"B_APC_Tracked_01_rcws_F",
	"B_APC_Wheeled_01_cannon_F",
	"B_Boat_Armed_01_minigun_F",
	"B_Boat_Transport_01_F",
	"B_G_Boat_Transport_01_F",
	"B_G_Offroad_01_armed_F",
	"B_G_Offroad_01_F",
	"B_G_Quadbike_01_F",
	"B_G_Van_01_transport_F",
	"B_Heli_Attack_01_F",
	"B_Heli_Light_01_armed_F",
	"B_Heli_Light_01_F",
	"B_Heli_Transport_01_camo_F",
	"B_Heli_Transport_01_F",
	"B_Lifeboat",
	"B_MBT_01_arty_F",
	"B_MBT_01_cannon_F",
	"B_MBT_01_mlrs_F",
	"B_MRAP_01_F",
	"B_MRAP_01_gmg_F",
	"B_MRAP_01_hmg_F",
	"B_MRAP_01_hmg_F", 
	"B_Plane_CAS_01_F",
	"B_Quadbike_01_F",
	"B_SDV_01_F",
	"B_Truck_01_ammo_F",
	"B_Truck_01_box_F",
	"B_Truck_01_covered_F",
	"B_Truck_01_fuel_F",
	"B_Truck_01_medical_F",
	"B_Truck_01_mover_F",
	"B_Truck_01_Repair_F",
	"B_Truck_01_transport_F",
	"B_UAV_02_CAS_F",
	"B_UAV_02_F",
	"B_UGV_01_F",
	"B_UGV_01_rcws_F",
	"C130J_US_EP1",
	"C_Boat_Civil_01_F",
	"C_Boat_Civil_police_01_F",
	"C_Boat_Civil_rescue_01_F",
	"C_Hatchback_01_F",
	"C_Hatchback_01_sport_F",
	"C_Offroad_01_F",
	"C_Quadbike_01_F",
	"C_Rubberboat",
	"C_SUV_01_F",
	"C_Van_01_box_F",
	"C_Van_01_box_F", 
	"C_Van_01_fuel_F",
	"C_Van_01_transport_F",
	"Hatchback_01_base_F",
	"Helicopter_Base_F",
	"I_APC_Wheeled_03_cannon_F",
	"I_Boat_Armed_01_minigun_F",
	"I_Boat_Transport_01_F",
	"I_G_Offroad_01_armed_F",
	"I_G_Offroad_01_F",
	"I_G_Quadbike_01_F",
	"I_G_Van_01_transport_F",
	"I_Heli_Transport_02_F",
	"I_MRAP_03_F",
	"I_MRAP_03_gmg_F",
	"I_MRAP_03_hmg_F",
	"I_Plane_Fighter_03_AA_F",
	"I_Plane_Fighter_03_CAS_F",
	"I_Quadbike_01_F",
	"I_SDV_01_F",
	"I_Truck_02_ammo_F",
	"I_Truck_02_box_F",
	"I_Truck_02_covered_F",
	"I_Truck_02_fuel_F",
	"I_Truck_02_medical_F",
	"I_Truck_02_transport_F",
	"I_UAV_02_CAS_F", 
	"I_UAV_02_F",
	"I_UGV_01_F",
	"I_UGV_01_rcws_F",
	"M1128_MGS_EP1",
	"M1133_MEV_EP1",
	"MRAP_01_base_F",
	"MRAP_02_base_F",
	"MRAP_03_base_F",
	"Offroad_01_base_F",
	"O_APC_Tracked_02_AA_F",
	"O_APC_Tracked_02_cannon_F",
	"O_APC_Wheeled_02_rcws_F",
	"O_Boat_Armed_01_hmg_F",
	"O_Boat_Transport_01_F",
	"O_Heli_Attack_02_black_F",
	"O_Heli_Attack_02_F",
	"O_Heli_Light_02_F",
	"O_Heli_Light_02_unarmed_F",
	"O_Lifeboat",
	"O_MBT_02_arty_F",
	"O_MBT_02_cannon_F",
	"O_MRAP_02_F",
	"O_MRAP_02_gmg_F",
	"O_MRAP_02_hmg_F",
	"O_MRAP_02_hmg_F", 
	"O_Plane_CAS_02_F",
	"O_Quadbike_01_F",
	"O_SDV_01_F",
	"O_Truck_02_Ammo_F",
	"O_Truck_02_box_F",
	"O_Truck_02_covered_F",
	"O_Truck_02_Fuel_F",
	"O_Truck_02_medical_F",
	"O_Truck_02_transport_F",
	"O_Truck_03_ammo_F",
	"O_Truck_03_fuel_F",
	"O_Truck_03_medical_F",
	"O_UAV_02_CAS_F",
	"O_UAV_02_F",
	"O_UGV_01_F",
	"O_UGV_01_rcws_F",
	"Plane_Base_F",
	"SDV_01_base_F",
	"SUV_01_base_F",
	"T34",
	"T55_TK_GUE_EP1",
	"Tank_F",
	"Truck_01_base_F",
	"Truck_02_base_F",
	"Van_01_base_F",
	"Wheeled_APC_F"
];

/****** LIFT WITH VEHICLE  ******/

/**
 * List of class names of air vehicles which can lift liftables objects.
 */
R3F_LOG_CFG_heliporteurs =
[
	"B_Heli_Attack_01_F",
	"B_Heli_Transport_01_camo_F",
	"B_Heli_Transport_01_F",
	"Helicopter_Base_F",
	"I_Heli_Transport_02_F",
	"O_Heli_Attack_02_black_F",
	"O_Heli_Attack_02_F"
];

/**
 * List of class names of liftables objects.
 */
R3F_LOG_CFG_objets_heliportables =
[
	"Offroad_01_base_F",
	"Van_01_base_F",
	"MRAP_01_base_F",
	"MRAP_02_base_F",
	"MRAP_03_base_F",
	"Truck_01_base_F",
	"Truck_02_base_F",
	"Wheeled_APC_F",
	"Tank_F",
	"C_Hatchback_01_F",
	"C_Hatchback_01_sport_F",
	"C_SUV_01_F",
	"C_Offroad_01_F",
	"I_G_Offroad_01_F",
	"C_Van_01_box_F",
	"C_Van_01_transport_F",
	"I_G_Van_01_transport_F",
	"O_Truck_02_covered_F",
	"I_Truck_02_covered_F",
	"O_Truck_02_transport_F",
	"I_Truck_02_transport_F",
	"I_G_Offroad_01_armed_F",
	"I_Truck_02_Fuel_F",
	"O_Truck_02_Fuel_F",
	"I_Truck_02_medical_F",
	"O_Truck_02_medical_F",
	"B_MRAP_01_F",
	"O_MRAP_02_F",
	"I_MRAP_03_F",
	"ArmoredSUV_PMC",
	"BAF_Jackal2_L2A1_D",
	"BAF_Jackal2_L2A1_w",
	"BMP3",
	"B_APC_Tracked_01_AA_F",
	"B_APC_Tracked_01_CRV_F",
	"B_APC_Tracked_01_rcws_F",
	"B_APC_Wheeled_01_cannon_F",
	"B_MBT_01_arty_F",
	"B_MBT_01_cannon_F",
	"B_MBT_01_mlrs_F",
	"B_MRAP_01_F",
	"B_MRAP_01_gmg_F",
	"B_MRAP_01_hmg_F",
	"B_MRAP_01_hmg_F", 
	"B_Truck_01_ammo_F",
	"B_Truck_01_box_F",
	"B_Truck_01_covered_F",
	"B_Truck_01_fuel_F",
	"B_Truck_01_medical_F",
	"B_Truck_01_mover_F",
	"B_Truck_01_Repair_F",
	"B_Truck_01_transport_F",
	"C_Hatchback_01_F",
	"C_Hatchback_01_sport_F",
	"C_Offroad_01_F",
	"O_MBT_02_arty_F",
	"O_MBT_02_cannon_F",
	"O_MRAP_02_F",
	"O_MRAP_02_gmg_F",
	"O_MRAP_02_hmg_F",
	"O_MRAP_02_hmg_F", 
	"C_Van_01_box_F",
	"C_Van_01_box_F", 
	"C_Van_01_fuel_F",
	"C_Van_01_transport_F",
	"Hatchback_01_base_F",
	"I_APC_Wheeled_03_cannon_F",
	"I_G_Offroad_01_armed_F",
	"I_G_Offroad_01_F",
	"I_MRAP_03_F",
	"I_MRAP_03_gmg_F",
	"I_MRAP_03_hmg_F",
	"I_Truck_02_ammo_F",
	"I_Truck_02_box_F",
	"I_Truck_02_covered_F",
	"I_Truck_02_fuel_F",
	"I_Truck_02_medical_F",
	"I_Truck_02_transport_F",
	"M1128_MGS_EP1",
	"M1133_MEV_EP1",
	"MRAP_01_base_F",
	"MRAP_02_base_F",
	"MRAP_03_base_F",
	"Offroad_01_base_F",
	"O_APC_Tracked_02_AA_F",
	"O_APC_Tracked_02_cannon_F",
	"O_APC_Wheeled_02_rcws_F",
	"O_MBT_02_arty_F",
	"O_MBT_02_cannon_F",
	"O_MRAP_02_F",
	"O_MRAP_02_gmg_F",
	"O_MRAP_02_hmg_F",
	"O_MRAP_02_hmg_F", 
	"O_Truck_02_Ammo_F",
	"O_Truck_02_box_F",
	"O_Truck_02_covered_F",
	"O_Truck_02_Fuel_F",
	"O_Truck_02_medical_F",
	"O_Truck_02_transport_F",
	"O_Truck_03_ammo_F",
	"O_Truck_03_fuel_F",
	"O_Truck_03_medical_F",
	"T34",
	"T55_TK_GUE_EP1",
	"Tank_F",
	"Truck_01_base_F",
	"Truck_02_base_F",
	"Van_01_base_F",
	"Wheeled_APC_F"	
];


/****** LOAD IN VEHICLE / CHARGER DANS LE VEHICULE ******/


/**
 * List of class names of (ground or air) vehicles which can transport transportables objects.
 * The second element of the arrays is the load capacity (in relation with the capacity cost of the objects).
 */
R3F_LOG_CFG_transporteurs =
[
	["Quadbike_01_base_F", 5],
	["Hatchback_01_base_F", 10],
	["SUV_01_base_F", 20],
	["Offroad_01_base_F", 30],
	["Van_01_base_F", 40],
	["MRAP_01_base_F", 20],
	["MRAP_02_base_F", 20],
	["MRAP_03_base_F", 20],
	["Truck_F", 75],
	["Wheeled_APC_F", 30],
	["Tank_F", 30],
	["Rubber_duck_base_F", 10],
	["Boat_Civil_01_base_F", 10],
	["Boat_Armed_01_base_F", 20],
	["Heli_Light_01_base_F", 10],
	["Heli_Light_02_base_F", 20],
	["Heli_Transport_01_base_F", 25],
	["Heli_Transport_02_base_F", 30],
	["Heli_Attack_01_base_F", 10],
	["Heli_Attack_02_base_F", 20],
	["O_Truck_03_fuel_F"],
	["O_Truck_03_ammo_F"],
	["O_Truck_03_medical_F"]
];

 
R3F_LOG_CFG_objets_transportables = 
[
	["StaticWeapon", 5],
	["Box_NATO_Wps_F", 5],
	["Box_NATO_WpsLaunch_F", 5],
	["Box_NATO_WpsSpecial_F", 5],
	["B_supplyCrate_F", 5],
	["Box_NATO_Support_F", 5],
	["Box_IND_Wps_F", 5],
	["Box_IND_WpsLaunch_F", 5],
	["Box_IND_WpsSpecial_F", 5],
	["I_supplyCrate_F", 5],
	["Box_IND_Support_F", 5],
	["Box_EAST_Wps_F", 5],
	["Box_EAST_WpsLaunch_F", 5],
	["Box_EAST_WpsSpecial_F", 5],
	["O_supplyCrate_F", 5],
	["Box_EAST_Support_F", 5],
	["ReammoBox_F", 3],
	["Quadbike_01_base_F", 10],
	["Rubber_duck_base_F", 10],
	["UAV_01_base_F", 2],
	["Land_BagBunker_Large_F", 10],
	["Land_BagBunker_Small_F", 5],
	["Land_BagBunker_Tower_F", 7],
	["Land_BagFence_Corner_F", 2],
	["Land_BagFence_End_F", 2],
	["Land_BagFence_Long_F", 3],
	["Land_BagFence_Round_F", 2],
	["Land_BagFence_Short_F", 2],
	["Land_BarGate_F", 3],
	["Land_Canal_WallSmall_10m_F", 4],
	["Land_Canal_Wall_Stairs_F", 3],
	["Land_CargoBox_V1_F", 5],
	["Land_Cargo_Patrol_V1_F", 7],
	["Land_Cargo_Tower_V1_F", 30],
	["Land_CncBarrier_F", 4],
	["Land_CncBarrierMedium_F", 4],
	["Land_CncBarrierMedium4_F", 4],
	["Land_CncShelter_F", 2],
	["Land_CncWall1_F", 3],
	["Land_CncWall4_F", 5],
	["Land_Crash_barrier_F", 5],
	["Land_HBarrierBig_F", 5],
	["Land_HBarrierTower_F", 8],
	["Land_HBarrierWall4_F", 4],
	["Land_HBarrierWall6_F", 6],
	["Land_HBarrier_1_F", 3],
	["Land_HBarrier_3_F", 4],
	["Land_HBarrier_5_F", 5],
	["Land_LampHarbour_F", 2],
	["Land_LampShabby_F", 2],
	["Land_MetalBarrel_F", 2],
	["Land_Mil_ConcreteWall_F", 5],
	["Land_Mil_WallBig_4m_F", 5],
	["Land_Obstacle_Ramp_F", 5],
	["Land_Pipes_large_F", 5],
	["Land_RampConcreteHigh_F", 6],
	["Land_RampConcrete_F", 5],
	["Land_Razorwire_F", 5],
	["Land_Sacks_goods_F", 2],
	["Land_Scaffolding_F", 5],
	["Land_Shoot_House_Wall_F", 3],
	["Land_Stone_8m_F", 5],
	["Land_ToiletBox_F", 2],
	["Land_BarrelWater_F", 2],
	["CamoNet_INDP_open_F",2],
	["CamoNet_INDP_big_F",2]
];

/****** MOVABLE-BY-PLAYER OBJECTS / OBJETS DEPLACABLES PAR LE JOUEUR ******/

R3F_LOG_CFG_objects_movables =
[
	"StaticWeapon",
	"ReammoBox_F",
	"Quadbike_01_base_F",
	"Rubber_duck_base_F",
	"SDV_01_base_F",
	"UAV_01_base_F",
	"Land_BagBunker_Large_F",
	"Land_BagBunker_Small_F",
	"Land_BagBunker_Tower_F",
	"Land_BagFence_Corner_F",
	"Land_BagFence_End_F",
	"Land_BagFence_Long_F",
	"Land_BagFence_Round_F",
	"Land_BagFence_Short_F",
	"Land_BarGate_F",
	"Land_Canal_WallSmall_10m_F",
	"Land_Canal_Wall_Stairs_F",
	"Land_CargoBox_V1_F",
	"Land_Cargo_Patrol_V1_F",
	"Land_Cargo_Tower_V1_F",
	"Land_CncBarrier_F",
	"Land_CncBarrierMedium_F",
	"Land_CncBarrierMedium4_F",
	"Land_CncShelter_F",
	"Land_CncWall1_F",
	"Land_CncWall4_F",
	"Land_Crash_barrier_F",
	"Land_HBarrierBig_F",
	"Land_HBarrierTower_F",
	"Land_HBarrierWall4_F",
	"Land_HBarrierWall6_F",
	"Land_HBarrier_1_F",
	"Land_HBarrier_3_F",
	"Land_HBarrier_5_F",
	"Land_LampHarbour_F",
	"Land_LampShabby_F",
	"Land_MetalBarrel_F",
	"Land_Mil_ConcreteWall_F",
	"Land_Mil_WallBig_4m_F",
	"Land_Obstacle_Ramp_F",
	"Land_Pipes_large_F",
	"Land_RampConcreteHigh_F",
	"Land_RampConcrete_F",
	"Land_Razorwire_F",
	"Land_Sacks_goods_F",
	"Land_Scaffolding_F",
	"Land_Shoot_House_Wall_F",
	"Land_Stone_8m_F",
	"Land_ToiletBox_F",
	"Land_BarrelWater_F",
	"CamoNet_INDP_open_F",
	"CamoNet_INDP_big_F"
];

R3F_LOG_CFG_objets_lockablevehicles =
[
	"ArmoredSUV_PMC",
	"BAF_Jackal2_L2A1_D",
	"BAF_Jackal2_L2A1_w",
	"BMP3",
	"Boat_Armed_01_base_F",
	"BTR40_MG_TK_GUE_EP1",
	"B_APC_Tracked_01_AA_F",
	"B_APC_Tracked_01_CRV_F",
	"B_APC_Tracked_01_rcws_F",
	"B_APC_Wheeled_01_cannon_F",
	"B_Boat_Armed_01_minigun_F",
	"B_Boat_Transport_01_F",
	"B_G_Boat_Transport_01_F",
	"B_G_Offroad_01_armed_F",
	"B_G_Offroad_01_F",
	"B_G_Quadbike_01_F",
	"B_G_Van_01_transport_F",
	"B_Heli_Attack_01_F",
	"B_Heli_Light_01_armed_F",
	"B_Heli_Light_01_F",
	"B_Heli_Transport_01_camo_F",
	"B_Heli_Transport_01_F",
	"B_Lifeboat",
	"B_MBT_01_arty_F",
	"B_MBT_01_cannon_F",
	"B_MBT_01_mlrs_F",
	"B_MRAP_01_F",
	"B_MRAP_01_gmg_F",
	"B_MRAP_01_hmg_F",
	"B_MRAP_01_hmg_F", 
	"B_Plane_CAS_01_F",
	"B_Quadbike_01_F",
	"B_SDV_01_F",
	"B_Truck_01_ammo_F",
	"B_Truck_01_box_F",
	"B_Truck_01_covered_F",
	"B_Truck_01_fuel_F",
	"B_Truck_01_medical_F",
	"B_Truck_01_mover_F",
	"B_Truck_01_Repair_F",
	"B_Truck_01_transport_F",
	"B_UAV_02_CAS_F",
	"B_UAV_02_F",
	"B_UGV_01_F",
	"B_UGV_01_rcws_F",
	"C130J_US_EP1",
	"C_Boat_Civil_01_F",
	"C_Boat_Civil_01_police_F",
	"C_Boat_Civil_01_rescue_F",
	"C_Hatchback_01_F",
	"C_Hatchback_01_sport_F",
	"C_Offroad_01_F",
	"C_Quadbike_01_F",
	"C_Rubberboat",
	"C_SUV_01_F",
	"C_Van_01_box_F",
	"C_Van_01_box_F", 
	"C_Van_01_fuel_F",
	"C_Van_01_transport_F",
	"Hatchback_01_base_F",
	"Helicopter_Base_F",
	"I_APC_Wheeled_03_cannon_F",
	"I_Boat_Armed_01_minigun_F",
	"I_Boat_Transport_01_F",
	"I_G_Offroad_01_armed_F",
	"I_G_Offroad_01_F",
	"I_G_Quadbike_01_F",
	"I_G_Van_01_transport_F",
	"I_Heli_Transport_02_F",
	"I_MRAP_03_F",
	"I_MRAP_03_gmg_F",
	"I_MRAP_03_hmg_F",
	"I_Plane_Fighter_03_AA_F",
	"I_Plane_Fighter_03_CAS_F",
	"I_Quadbike_01_F",
	"I_SDV_01_F",
	"I_Truck_02_ammo_F",
	"I_Truck_02_box_F",
	"I_Truck_02_covered_F",
	"I_Truck_02_fuel_F",
	"I_Truck_02_medical_F",
	"I_Truck_02_transport_F",
	"I_UAV_02_CAS_F", 
	"I_UAV_02_F",
	"I_UGV_01_F",
	"I_UGV_01_rcws_F",
	"M1128_MGS_EP1",
	"M1133_MEV_EP1",
	"MRAP_01_base_F",
	"MRAP_02_base_F",
	"MRAP_03_base_F",
	"Offroad_01_base_F",
	"O_APC_Tracked_02_AA_F",
	"O_APC_Tracked_02_cannon_F",
	"O_APC_Wheeled_02_rcws_F",
	"O_Boat_Armed_01_hmg_F",
	"O_Boat_Transport_01_F",
	"O_Heli_Attack_02_black_F",
	"O_Heli_Attack_02_F",
	"O_Heli_Light_02_F",
	"O_Heli_Light_02_unarmed_F",
	"O_Lifeboat",
	"O_MBT_02_arty_F",
	"O_MBT_02_cannon_F",
	"O_MRAP_02_F",
	"O_MRAP_02_gmg_F",
	"O_MRAP_02_hmg_F",
	"O_MRAP_02_hmg_F", 
	"O_Plane_CAS_02_F",
	"O_Quadbike_01_F",
	"O_SDV_01_F",
	"O_Truck_02_Ammo_F",
	"O_Truck_02_box_F",
	"O_Truck_02_covered_F",
	"O_Truck_02_Fuel_F",
	"O_Truck_02_medical_F",
	"O_Truck_02_transport_F",
	"O_Truck_03_ammo_F",
	"O_Truck_03_fuel_F",
	"O_Truck_03_medical_F",
	"O_UAV_02_CAS_F",
	"O_UAV_02_F",
	"O_UGV_01_F",
	"O_UGV_01_rcws_F",
	"Plane_Base_F",
	"SDV_01_base_F",
	"SUV_01_base_F",
	"T34",
	"T55_TK_GUE_EP1",
	"Tank_F",
	"Truck_01_base_F",
	"Truck_02_base_F",
	"Van_01_base_F",
	"Wheeled_APC_F"
];
